USE employees;
-- SELECT * FROM employees WHERE first_name IN ('Irena', 'Vidya', 'Maya') ORDER BY last_name ASC, first_name ASC;
-- SELECT COUNT(*) FROM employees WHERE first_name IN ('Irena', 'Vidya', 'Maya') ORDER BY last_name ASC, first_name ASC;
-- SELECT * FROM employees WHERE first_name IN ('Irena', 'Vidya', 'Maya') ORDER BY last_name DESC, first_name DESC;
-- SELECT COUNT(*) FROM employees WHERE first_name IN ('Irena', 'Vidya', 'Maya') ORDER BY last_name DESC, first_name DESC;
-- SELECT * FROM employees WHERE last_name LIKE 'E%';
-- SELECT COUNT(*) FROM employees WHERE last_name LIKE 'E%';
-- SELECT * FROM employees WHERE last_name LIKE 'q%' OR last_name LIKE '%q%' OR last_name LIKE '%q';
-- SELECT COUNT(*) FROM employees WHERE last_name LIKE 'q%' OR last_name LIKE '%q%' OR last_name LIKE '%q';
-- SELECT * FROM employees WHERE first_name IN ('Irena') OR first_name IN ('Vidya') OR first_name IN ('Maya');
-- SELECT COUNT(*) FROM employees WHERE first_name IN ('Irena') OR first_name IN ('Vidya') OR first_name IN ('Maya');
-- SELECT * FROM employees WHERE (first_name = 'Irena' OR first_name = 'Vidya' OR first_name = 'Maya') AND gender = 'M';
-- SELECT COUNT(*) FROM employees WHERE (first_name = 'Irena' OR first_name = 'Vidya' OR first_name = 'Maya') AND gender = 'M';
SELECT CONCAT(first_name, ' ', last_name) FROM employees WHERE last_name LIKE 'E%' OR last_name LIKE '%e' ORDER BY emp_no ASC;
SELECT COUNT(CONCAT(first_name, ' ', last_name)) FROM employees WHERE last_name LIKE 'E%' OR last_name LIKE '%e' ORDER BY emp_no ASC;
-- SELECT * FROM employees WHERE last_name LIKE 'E%' OR last_name LIKE '%e' ORDER BY emp_no DESC;
-- SELECT COUNT(*) FROM employees WHERE last_name LIKE 'E%' OR last_name LIKE '%e' ORDER BY emp_no DESC;
-- SELECT * FROM employees WHERE last_name LIKE 'E%' AND last_name LIKE '%e';
-- SELECT COUNT(*) FROM employees WHERE last_name LIKE 'E%' AND last_name LIKE '%e';
-- SELECT * FROM employees WHERE last_name LIKE 'E%' AND last_name LIKE '%e';
-- SELECT COUNT(*) FROM employees WHERE last_name LIKE 'E%' AND last_name LIKE '%e';
-- SELECT * FROM employees WHERE (last_name LIKE 'q%' OR last_name LIKE '%q%' OR last_name LIKE '%q') AND NOT (last_name LIKE 'qu%' OR last_name LIKE '%qu%' OR last_name LIKE '%qu');
-- SELECT COUNT(*) FROM employees WHERE (last_name LIKE 'q%' OR last_name LIKE '%q%' OR last_name LIKE '%q') AND NOT (last_name LIKE 'qu%' OR last_name LIKE '%qu%' OR last_name LIKE '%qu');
SELECT * FROM employees WHERE month(birth_date) = 12 AND day(birth_date) = 25;
SELECT COUNT(*) FROM employees WHERE month(birth_date) = 12 AND day(birth_date) = 25;
SELECT * FROM employees WHERE ((month(birth_date) = 12 AND day(birth_date) = 25) AND (year(hire_date) >= 1990));
SELECT COUNT(*) FROM employees WHERE ((month(birth_date) = 12 AND day(birth_date) = 25) AND (year(hire_date) >= 1990));
SELECT CONCAT(first_name, ' ', last_name), DATEDIFF(now(), hire_date) FROM employees WHERE ((month(birth_date) = 12 AND day(birth_date) = 25) AND (year(hire_date) >= 1990));
